import os
from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from drtc_app.models import ServicePackage, CustomerReview, Booking
from django.utils import timezone
from datetime import timedelta


class Command(BaseCommand):
    help = "Seed database with official DRTC service packages and reviews"

    def handle(self, *args, **options):
        self.stdout.write("Seeding DRTC data...")

        # 1. Superuser
        if not User.objects.filter(username="admin").exists():
            User.objects.create_superuser("admin", "drtcservice@gmail.com", "admin123")
            self.stdout.write(self.style.SUCCESS("Superuser 'admin' created (password: admin123)"))

        # 2. Official Packages (from official DRTC price chart - all 25 tiers)
        packages_data = [
            {
                "capacity": "500 L",
                "capacity_liters": 500,
                "price": 250.00,
                "original_mrp": 360.00,
                "is_popular": False,
                "ideal_for": "Small 1-BHK flats & individual homes",
                "duration_mins": 45,
                "badge_text": "",
                "features_list": "Mechanized Dewatering\nSludge & Mud Extraction\nHigh Pressure Rotary Jet Scrub\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization",
                "order": 1,
            },
            {
                "capacity": "1000 L",
                "capacity_liters": 1000,
                "price": 400.00,
                "original_mrp": 600.00,
                "is_popular": True,
                "ideal_for": "Standard 2-BHK flats & residential homes",
                "duration_mins": 60,
                "badge_text": "",
                "features_list": "Full 6-Stage Scientific Cleaning\nComplete Sludge Removal\nRotary Jet Pressure Wash (Walls & Base)\nAnti-Bacterial Chemical Spray\nUV Germicidal Radiation Sterilization\nClean Odorless Water Guarantee",
                "order": 2,
            },
            {
                "capacity": "2000 L",
                "capacity_liters": 2000,
                "price": 650.00,
                "original_mrp": 940.00,
                "is_popular": False,
                "ideal_for": "3-BHK homes, small commercial buildings",
                "duration_mins": 90,
                "badge_text": "",
                "features_list": "Full 6-Stage Scientific Cleaning\nDeep Vacuum Sludge Extraction\nHeavy Duty Jet Wall Scrubbing\nOrganic Disinfection Treatment\nUV Lamp Sanitization\nNo Water Wastage Tech",
                "order": 3,
            },
            {
                "capacity": "3000 L",
                "capacity_liters": 3000,
                "price": 900.00,
                "original_mrp": 1300.00,
                "is_popular": False,
                "ideal_for": "4-5 BHK bungalows & multi-family homes",
                "duration_mins": 120,
                "badge_text": "",
                "features_list": "Multi-Layer Rotary High Pressure Jet\nIndustrial Sludge Suction\nBio-Enzyme & Anti-Bacterial Wash\nUV Ray Pathogen Elimination\nComplete Tank Inspection Report",
                "order": 4,
            },
            {
                "capacity": "5000 L",
                "capacity_liters": 5000,
                "price": 1100.00,
                "original_mrp": 1590.00,
                "is_popular": False,
                "ideal_for": "Large villas, hotels & commercial spaces",
                "duration_mins": 180,
                "badge_text": "",
                "features_list": "Full Commercial Grade 6-Stage Process\nDual-Pump High Flow Dewatering\nIndustrial Slurry Vacuuming\nDouble-Pass UV Sterilization\nFormal Quality & Hygiene Clearance",
                "order": 5,
            },
            {
                "capacity": "8000 L",
                "capacity_liters": 8000,
                "price": 1680.00,
                "original_mrp": 2430.00,
                "is_popular": False,
                "ideal_for": "Large residential buildings & factories",
                "duration_mins": 210,
                "badge_text": "",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 6,
            },
            {
                "capacity": "10,000 L",
                "capacity_liters": 10000,
                "price": 2200.00,
                "original_mrp": 3180.00,
                "is_popular": False,
                "ideal_for": "Commercial complexes & large apartments",
                "duration_mins": 240,
                "badge_text": "",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 7,
            },
            {
                "capacity": "15,000 L",
                "capacity_liters": 15000,
                "price": 3080.00,
                "original_mrp": 4450.00,
                "is_popular": False,
                "ideal_for": "Society overhead / underground tanks",
                "duration_mins": 270,
                "badge_text": "",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 8,
            },
            {
                "capacity": "20,000 L",
                "capacity_liters": 20000,
                "price": 3820.00,
                "original_mrp": 5520.00,
                "is_popular": False,
                "ideal_for": "Large housing societies & institutions",
                "duration_mins": 300,
                "badge_text": "",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 9,
            },
            {
                "capacity": "25,000 L",
                "capacity_liters": 25000,
                "price": 4740.00,
                "original_mrp": 6850.00,
                "is_popular": False,
                "ideal_for": "Industrial facilities & large societies",
                "duration_mins": 330,
                "badge_text": "",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 10,
            },
            {
                "capacity": "30,000 L",
                "capacity_liters": 30000,
                "price": 5490.00,
                "original_mrp": 7940.00,
                "is_popular": False,
                "ideal_for": "Commercial/industrial storage reservoirs",
                "duration_mins": 360,
                "badge_text": "",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 11,
            },
            {
                "capacity": "40,000 L",
                "capacity_liters": 40000,
                "price": 6390.00,
                "original_mrp": 9240.00,
                "is_popular": False,
                "ideal_for": "Large commercial/industrial complexes",
                "duration_mins": 420,
                "badge_text": "",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 12,
            },
            {
                "capacity": "45,000 L",
                "capacity_liters": 45000,
                "price": 7200.00,
                "original_mrp": 10400.00,
                "is_popular": False,
                "ideal_for": "Major industrial & institutional sumps",
                "duration_mins": 450,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 13,
            },
            {
                "capacity": "50,000 L",
                "capacity_liters": 50000,
                "price": 7600.00,
                "original_mrp": 10990.00,
                "is_popular": False,
                "ideal_for": "Major industrial & institutional sumps",
                "duration_mins": 480,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 14,
            },
            {
                "capacity": "60,000 L",
                "capacity_liters": 60000,
                "price": 8210.00,
                "original_mrp": 11870.00,
                "is_popular": False,
                "ideal_for": "Large industrial sumps & water storage",
                "duration_mins": 510,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 15,
            },
            {
                "capacity": "65,000 L",
                "capacity_liters": 65000,
                "price": 9000.00,
                "original_mrp": 13000.00,
                "is_popular": False,
                "ideal_for": "Large industrial storage & treatment tanks",
                "duration_mins": 540,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 16,
            },
            {
                "capacity": "70,000 L",
                "capacity_liters": 70000,
                "price": 9600.00,
                "original_mrp": 13880.00,
                "is_popular": False,
                "ideal_for": "Large industrial storage & treatment tanks",
                "duration_mins": 570,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 17,
            },
            {
                "capacity": "80,000 L",
                "capacity_liters": 80000,
                "price": 11210.00,
                "original_mrp": 16200.00,
                "is_popular": False,
                "ideal_for": "Very large industrial storage tanks",
                "duration_mins": 600,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 18,
            },
            {
                "capacity": "85,000 L",
                "capacity_liters": 85000,
                "price": 13870.00,
                "original_mrp": 20040.00,
                "is_popular": False,
                "ideal_for": "Very large industrial & municipal tanks",
                "duration_mins": 630,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 19,
            },
            {
                "capacity": "90,000 L",
                "capacity_liters": 90000,
                "price": 15500.00,
                "original_mrp": 22400.00,
                "is_popular": False,
                "ideal_for": "Very large industrial & municipal tanks",
                "duration_mins": 660,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 20,
            },
            {
                "capacity": "1,00,000 L",
                "capacity_liters": 100000,
                "price": 18780.00,
                "original_mrp": 27150.00,
                "is_popular": False,
                "ideal_for": "Municipal & large institutional water tanks",
                "duration_mins": 720,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 21,
            },
            {
                "capacity": "1,05,000 L",
                "capacity_liters": 105000,
                "price": 20810.00,
                "original_mrp": 30070.00,
                "is_popular": False,
                "ideal_for": "Large-scale municipal & industrial tanks",
                "duration_mins": 750,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 22,
            },
            {
                "capacity": "1,20,000 L",
                "capacity_liters": 120000,
                "price": 25950.00,
                "original_mrp": 37500.00,
                "is_popular": False,
                "ideal_for": "Large-scale municipal & industrial tanks",
                "duration_mins": 780,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 23,
            },
            {
                "capacity": "1,25,000 L",
                "capacity_liters": 125000,
                "price": 29590.00,
                "original_mrp": 42780.00,
                "is_popular": False,
                "ideal_for": "Mega industrial & municipal water reservoirs",
                "duration_mins": 840,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 24,
            },
            {
                "capacity": "1,50,000 L",
                "capacity_liters": 150000,
                "price": 36830.00,
                "original_mrp": 53250.00,
                "is_popular": False,
                "ideal_for": "Mega industrial & municipal water reservoirs",
                "duration_mins": 900,
                "badge_text": "Range Pack",
                "features_list": "High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee",
                "order": 25,
            },
        ]

        for pkg in packages_data:
            obj, created = ServicePackage.objects.update_or_create(
                capacity=pkg["capacity"],
                defaults=pkg
            )
            action = "Created" if created else "Updated"
            self.stdout.write(f"{action} package: {obj.capacity} @ Rs.{obj.price}")

        # 3. Authentic Customer Reviews
        reviews_data = [
            {
                "customer_name": "Rajesh Sharma",
                "locality": "Shantinagar, Gamharia",
                "tank_capacity": "1000 L Sintex Tank",
                "rating": 5,
                "review_title": "Remarkable cleaning! Water is crystal clear now",
                "comment": "Dinesh ji and Rakesh arrived promptly at our house near Jhanda Chowk. The amount of mud they removed from the bottom of our 1000L tank was unbelievable. Their high-pressure jet and UV treatment are very professional. Highly recommended!",
                "date_added": timezone.now().date() - timedelta(days=3),
            },
            {
                "customer_name": "Amit Mahato",
                "locality": "Gamharia Industrial Area",
                "tank_capacity": "5000 L Concrete Sump",
                "rating": 5,
                "review_title": "Best commercial tank cleaning service in town",
                "comment": "We booked them for our 5000L factory overhead tank. Their mechanized pumps and vacuum suction cleaned the entire tank within 3 hours. Transparent price of ₹1100 with zero hassle. Exceptional work!",
                "date_added": timezone.now().date() - timedelta(days=6),
            },
            {
                "customer_name": "Pooja Verma",
                "locality": "Adityapur, Jamshedpur",
                "tank_capacity": "500 L Overhead Tank",
                "rating": 5,
                "review_title": "Very affordable at ₹250 and extremely polite staff",
                "comment": "Quick booking on WhatsApp and arrived on time. The operator Rakesh wore proper boots and mask. After cleaning, they sanitized the tank thoroughly with food-grade spray and UV lamp. Safe water for my baby!",
                "date_added": timezone.now().date() - timedelta(days=9),
            },
            {
                "customer_name": "Sanjay Singh",
                "locality": "Lal Building, Gamharia",
                "tank_capacity": "2000 L RCC Sump",
                "rating": 5,
                "review_title": "Professional de-sludging without wasting extra water",
                "comment": "Our underground sump had thick algae and sediment buildup for 2 years. DRTC’s slurry vacuum machine took out everything without messing up our courtyard. Honest pricing of ₹650.",
                "date_added": timezone.now().date() - timedelta(days=12),
            },
        ]

        for rev in reviews_data:
            CustomerReview.objects.get_or_create(
                customer_name=rev["customer_name"],
                defaults=rev
            )

        # 4. Sample Booking for live tracking demo
        pkg_1000 = ServicePackage.objects.filter(capacity="1000 L").first()
        if not Booking.objects.filter(booking_id="DRTC-9821").exists():
            Booking.objects.create(
                booking_id="DRTC-9821",
                customer_name="Vikram Choudhary",
                customer_phone="9835123456",
                customer_email="vikram.c@gmail.com",
                package=pkg_1000,
                custom_capacity="1000 L",
                tank_type="OVERHEAD_PVC",
                number_of_tanks=1,
                total_amount=400.00,
                preferred_date=timezone.now().date() + timedelta(days=1),
                preferred_time_slot="08:00 AM - 11:00 AM",
                address="Plot 42, Near DAV Public School",
                landmark="Near Jhanda Chowk",
                area_locality="Shantinagar, Gamharia",
                payment_method="PAY_ON_SERVICE",
                payment_status="UNPAID",
                status="CONFIRMED",
                assigned_technician="Rakesh (Lead Operator)",
                notes="Overhead tank on 2nd floor roof terrace."
            )

        self.stdout.write(self.style.SUCCESS("DRTC seed data successfully loaded!"))
