# Generated by Django 6.0 on 2026-10-01 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(default='Tank Cleaning Inquiry', max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('locality', models.CharField(default='Gamharia, Jamshedpur', max_length=100)),
                ('tank_capacity', models.CharField(default='1000 L Overhead Tank', max_length=50)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_title', models.CharField(default='Exceptional Cleaning & Safe Water!', max_length=120)),
                ('comment', models.TextField()),
                ('verified_customer', models.BooleanField(default=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(help_text='e.g. 500 Liter, 1000 L, 2000 L, 3000 L, 5000 L', max_length=50)),
                ('capacity_liters', models.PositiveIntegerField(help_text='Numeric capacity in liters')),
                ('price', models.DecimalField(decimal_places=2, help_text='Official price in INR', max_digits=8)),
                ('original_mrp', models.DecimalField(decimal_places=2, help_text='Standard market price / MRP', max_digits=8)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as most popular / recommended')),
                ('ideal_for', models.CharField(help_text='e.g. 1-2 BHK flats, 3-4 BHK bungalows, commercial', max_length=150)),
                ('duration_mins', models.PositiveIntegerField(default=60, help_text='Estimated time in minutes')),
                ('features_list', models.TextField(default='High Pressure Rotary Jet Washing\nSludge & Silt Vacuum Extraction\nAnti-Bacterial UV Disinfection\nSafe Food-Grade Sterilization\nClean Water Guarantee', help_text='One feature per line')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. Best Value, Most Popular', max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['order', 'capacity_liters'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('custom_capacity', models.CharField(blank=True, help_text='e.g. 1000 L or custom capacity', max_length=100)),
                ('tank_type', models.CharField(choices=[('OVERHEAD_PVC', 'Overhead PVC / Sintex Tank'), ('UNDERGROUND_SUMP', 'Underground RCC / Concrete Sump'), ('LOFT_TANK', 'Loft / Indoor Tank'), ('COMMERCIAL_STORAGE', 'Commercial Storage Reservoir'), ('MULTIPLE_TANKS', 'Multiple Tanks Combo')], default='OVERHEAD_PVC', max_length=50)),
                ('number_of_tanks', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preferred_date', models.DateField(default=django.utils.timezone.now)),
                ('preferred_time_slot', models.CharField(default='08:00 AM - 11:00 AM', help_text='e.g. Morning (8 AM - 11 AM), Afternoon (11 AM - 2 PM), Evening (2 PM - 6 PM)', max_length=50)),
                ('address', models.TextField(help_text='House/Flat No, Street, Colony')),
                ('landmark', models.CharField(blank=True, help_text='e.g. Near Jhanda Chowk, Lal Building, Gamharia', max_length=120)),
                ('area_locality', models.CharField(default='Gamharia, Jamshedpur', max_length=120)),
                ('pincode', models.CharField(default='832108', max_length=10)),
                ('payment_method', models.CharField(choices=[('PAY_ON_SERVICE', 'Pay After Cleaning (Cash / UPI on site)'), ('UPI_ADVANCE', 'Instant UPI / QR Code'), ('ONLINE', 'Online Payment')], default='PAY_ON_SERVICE', max_length=30)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid (Due upon completion)'), ('PAID', 'Paid in Full')], default='UNPAID', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed & Scheduled'), ('TECHNICIAN_ASSIGNED', 'Technician Assigned'), ('IN_PROGRESS', 'Cleaning In Progress'), ('COMPLETED', 'Service Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('assigned_technician', models.CharField(blank=True, default='Rakesh (Lead Operator)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='drtc_app.servicepackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
